# Generated by Django 3.1.4 on 2021-03-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candy',
            name='quantity',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candy',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
